### ISSUE TITLE
wine CentOS 8 install script different packages

### ISSUE THREAD

**Issue by nicrame** [zma/usefulscripts#9]
3 packages has been updated in CentOS 7 repo, that are used for fixing CentOS 8 script.
Just change:
dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/qt-4.8.7-3.el7_6.i686.rpm -y 2>&1 >> $log
dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/qt-x11-4.8.7-3.el7_6.i686.rpm -y 2>&1 >> $log
dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/qt-devel-4.8.7-3.el7_6.i686.rpm -y 2>&1 >> $log

into new versions from repo:
dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/qt-4.8.7-8.el7.i686.rpm -y 2>&1 >> $log

dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/qt-x11-4.8.7-8.el7.i686.rpm -y 2>&1 >> $log
dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/qt-devel-4.8.7-8.el7.i686.rpm -y 2>&1 >> $log

**Comment by zma** [comment]
Thanks @nicrame !
